// Dữ liệu danh mục thư viện. Claude cập nhật file này mỗi khi có bài mới.
// status: 2 = Đã hoàn thành (đã có bản dịch), 1 = Đang biên soạn, 0 = Chưa soạn / cần cập nhật
//
// "topic" = chủ đề bệnh/nhóm bệnh dùng để GOM NHÓM các bài trong cùng 1 chuyên khoa
// (ví dụ trong "nt" có các topic "Đái tháo đường", "Tuyến giáp", "Tuyến thượng thận";
// trong "tq" có topic "Rối loạn điện giải"...). Khi thêm 1 bài thuộc chủ đề CHƯA có
// trong chuyên khoa đó (ví dụ bài Viêm phổi đầu tiên trong "hh"), tự đặt tên topic mới
// hợp lý (ví dụ "Nhiễm trùng hô hấp") — không cần hỏi lại, trang sẽ tự tạo nhóm mới.
window.LIBRARY = {
  updated: "2026-10-06",
  dashboardUrl: "https://huuhuynh2k2-droid.github.io/on-thi-dashboard/",
  // "topic" mới trong "tm" (Tim mạch): "Kháng kết tập tiểu cầu" — nhóm này chưa từng có bài
  // nào trước đó nên tự tạo mới theo hướng dẫn ở trên.
  specialties: [
    { id: "tm",  name: "Tim mạch",             en: "Cardiology" },
    { id: "hh",  name: "Hô hấp",               en: "Pulmonology" },
    { id: "th",  name: "Tiêu hóa",             en: "Gastroenterology" },
    { id: "than",name: "Thận",                 en: "Nephrology" },
    { id: "cxk", name: "Cơ xương khớp",        en: "Rheumatology" },
    { id: "nt",  name: "Nội tiết",             en: "Endocrinology" },
    { id: "tk",  name: "Thần kinh",            en: "Neurology" },
    { id: "tq",  name: "Tổng quát",            en: "General Internal Medicine" },
    { id: "hscc",name: "Hồi sức – Cấp cứu",    en: "Critical Care & Emergency" },
    { id: "cls", name: "Cận lâm sàng",         en: "Laboratory & Diagnostics" }
  ],
  items: [
    // "topic" mới trong "th" (Tiêu hóa): "Xơ gan" — chuyên khoa "th" chưa có bài nào trước đó, tự tạo mới theo hướng dẫn ở trên.
    { id: "th-bang-bung-xo-gan-bsg2020", sp: "th", topic: "Xơ gan",
      title: "Báng bụng ở bệnh nhân xơ gan — Chẩn đoán, kỹ thuật chọc tháo dịch báng và điều trị",
      org: "BSG 2020 (Gut 2021) · slide BS Trần Tuấn Anh · bổ sung AASLD 2021/EASL 2018/Baveno VII", year: 2021,
      doi: "https://doi.org/10.1136/gutjnl-2020-321790", status: 2,
      cat: "Guideline · Thủ thuật · Bản tổng hợp/biên soạn lại · Hình gốc + 2 sơ đồ tự vẽ",
      note: "Cơ chế giữ muối nước (RAAS/giao cảm/ADH), phân độ báng ICA và tiêu chí báng kháng trị; chọc dò chẩn đoán (ống mẫu, SAAG × protein, ADA/BNP/TG/bilirubin dịch); đọc đại thể dịch báng (trong, vàng rơm, vàng chanh, đục, dưỡng chấp, máu, nâu mật) kèm hình thật; kỹ thuật chọc tháo: không ngưỡng INR/tiểu cầu, vị trí an toàn hố chậu trái cách đường giữa ≥ 8 cm & trên khớp mu ≥ 5 cm, Z-track, biến chứng, albumin 8 g/L khi > 5 L; SBP (PMN > 250, kháng sinh, albumin 1,5 → 1 g/kg, dự phòng); muối – lợi tiểu 100:40 – hạ Na; báng kháng trị (TIPS, NSBB, alfapump, giảm nhẹ); HRS-AKI; thoát vị rốn, tràn dịch màng phổi do gan; bảng so sánh BSG/AASLD/EASL và bẫy MCQ.",
      updated: "2026-10-05", url: "docs/bang-bung-xo-gan-choc-thao-dich-bang.html" },
    // "topic" mới trong "than" (Thận): "Tổn thương thận cấp" — chuyên khoa "than" chưa có bài nào trước đó, tự tạo mới theo hướng dẫn ở trên.
    { id: "than-kdigo2026-akiakd-ch1", sp: "than", topic: "Tổn thương thận cấp",
      title: "KDIGO 2026 AKI/AKD — Chương 1: Định nghĩa, Nhận diện, Phân loại (+ trẻ em, sơ sinh)",
      org: "KDIGO Clinical Practice Guideline (Public Review Draft, 3/2026)", year: 2026,
      doi: "https://kdigo.org/wp-content/uploads/2026/03/KDIGO-2026-AKI-AKD-Guideline-Public-Review-Draft-March-2026.pdf", status: 1,
      cat: "Guideline dự thảo (chưa chính thức) · Bản tổng hợp/viết lại (không dịch nguyên văn) · Sơ đồ tự vẽ",
      note: "Định nghĩa AKI (tiêu chí chức năng + cấu trúc, Bảng 1), hạn chế của creatinin/thể tích nước tiểu (Bảng 2), cách chọn creatinin nền phân cấp (Hình 1 tự vẽ), vai trò biomarker tổn thương (TIMP-2×IGFBP7, NGAL — Bảng 3-4), Khuyến cáo 1.1.1 (cystatin C, Grade 2B), phân độ 3 trục C/U/B (Bảng 6), AKI tạm thời/kéo dài (Bảng 7), định nghĩa AKD lấp khoảng trống AKI-CKD (Bảng 9, Hình 2 tự vẽ), tiêu chí phục hồi (Bảng 10), AKI tái phát, và toàn bộ phần trẻ em/sơ sinh (baseline phân cấp riêng — Hình 3 tự vẽ, tiêu chí AKI sơ sinh do vắng hiện tượng giảm SCr sinh lý — Bảng 12-13). Đây là bản DỰ THẢO lấy ý kiến công khai, ngưỡng có thể thay đổi trước khi ban hành chính thức — KDIGO 2012 vẫn là chuẩn hiện hành cho đến khi có bản cuối.",
      updated: "2026-09-29", url: "docs/kdigo-2026-aki-akd-chuong1.html" },

    // "topic" mới trong "tm": "Suy tim" — nhóm này chưa từng có bài nào trước đó nên tự tạo mới theo hướng dẫn ở trên.
    { id: "tm-hfpef-chau-a-2026", sp: "tm", topic: "Suy tim", title: "HFpEF tại châu Á — Đặc điểm lâm sàng và Chiến lược điều trị",
      org: "Tromp J, et al. JACC: Asia 2026 (State-of-the-Art Review)", year: 2026, doi: "https://doi.org/10.1016/j.jacasi.2026.08.009", status: 2,
      cat: "Suy tim phân suất tống máu bảo tồn · Tổng quan",
      note: "Bản dịch đầy đủ kèm Central Illustration (hình gốc): chẩn đoán HFpEF tại châu Á (HFA-PEFF/H2FPEF kém nhạy ở người châu Á, Bảng 1 so sánh 7 hướng dẫn quốc tế/khu vực, AI-ECG và siêu âm tim hỗ trợ AI); 3 phân nhóm chính (cao tuổi/rung nhĩ/tăng huyết áp, béo phì, \"gầy-đái tháo đường\" đặc thù châu Á với béo bụng ở BMI thấp); kết cục và tử vong theo vùng (Đông Nam Á vs Đông Bắc Á); điều trị: thất bại của ACEi/ARB/MRA cổ điển, bước đột phá SGLT2i (EMPEROR-Preserved, DELIVER), ns-MRA (FINEARTS-HF), GLP-1RA (STEP-HFpEF, SUMMIT) và giới hạn ngưỡng BMI phương Tây khi áp dụng cho người châu Á, khoảng trống chi phí-hiệu quả.",
      updated: "2026-09-28", url: "docs/hfpef-chau-a-2026.html" },

    { id: "tm-hfpef-nejm-2025", sp: "tm", topic: "Suy tim", title: "Suy tim phân suất tống máu bảo tồn (HFpEF) — Clinical Practice",
      org: "Cannata A, McDonagh TA. N Engl J Med 2025;392:173-84 (bản dịch: CLB Nội khoa ĐHYD TP.HCM)", year: 2025, doi: "https://doi.org/10.1056/NEJMcp2305181", status: 2,
      cat: "Suy tim phân suất tống máu bảo tồn · Clinical Practice",
      note: "Bản dịch đầy đủ (CLB Nội khoa – ĐH Y Dược TP.HCM: Minh Khôi Y20, Thiên Nhi Y21, Minh Quang Y22, Hoàng Phúc Y24) kèm 2 hình gốc: Hình 1 — lưu đồ thực hành chẩn đoán HFpEF (loại trừ các bệnh lý giả dạng: bệnh tim thoái hóa dạng bột, sarcoidosis, phì đại, bẩm sinh...; bảng chỉ điểm bất thường tim mạch lúc nghỉ/gắng sức); Hình 2 — forest plot hiệu quả SGLT2i/RAS-i/MRA trên 8 thử nghiệm (DELIVER, EMPEROR-Preserved, SOLOIST-WHF, PARAGON, CHARM, TOPCAT, FINEARTS-HF). Nội dung: dịch tễ và tiên lượng, chẩn đoán (NT-proBNP, loại trừ bệnh giả dạng, CMR/đo huyết động xâm lấn), điều trị bằng thuốc (RAS-i, ARNI — PARAGON-HF/PARAGLIDE-HF/PARALLAX, MRA — TOPCAT/FINEARTS-HF, chẹn beta, lợi tiểu, SGLT2i — EMPEROR-Preserved/DELIVER, GLP-1RA — STEP-HFpEF/SUMMIT), thiết bị (CardioMEMS, shunt liên nhĩ), Bảng 1 so sánh khuyến cáo liều dùng theo 5 guideline quốc tế (ACC/AHA, ESC, CCS-CCFS, JCS/JHFS, NHFA-CSANZ), và hướng dẫn thực hành lâm sàng quay lại ca bệnh mở đầu.",
      updated: "2026-09-28", url: "docs/hfpef-nejm-2025-clb-noikhoa.html" },

    { id: "tm-esc2026-suytim", sp: "tm", topic: "Suy tim", title: "ESC 2026 Guideline Suy tim — Bản tổng hợp/viết lại đầy đủ (5 phần)",
      org: "ESC Guidelines (Køber L, Adamo M, et al. Eur Heart J 2026)", year: 2026, doi: "https://doi.org/10.1093/eurheartj/ehag100", status: 2,
      cat: "Guideline mới nhất · Bản tổng hợp/viết lại (không dịch nguyên văn) · Trang chỉ mục 5 phần",
      note: "Trang chỉ mục dẫn vào bản tổng hợp và viết lại (kèm giải thích cơ chế, so sánh, bẫy thi MCQ, sơ đồ tự vẽ — không dịch nguyên văn) toàn bộ khuyến cáo ESC 2026 về suy tim, chia 5 phần: Phần 1 — định nghĩa/dịch tễ/phân loại/dự phòng/chẩn đoán (chương 1–5, gồm khung Class/Level mới, bỏ HFmrEF, đổi 'suy tim cấp' → 'suy tim mất bù', khung FMT/AMT/GDIT). Phần 2 — điều trị dược lý & can thiệp thiết bị suy tim mạn (chương 6: FMT/AMT theo kiểu hình LVEF, ICD/CRT, tạo nhịp hệ dẫn truyền). Phần 3 — suy tim mất bù (chương 7: 4 thể lâm sàng, SCAI A-E, thuật toán lợi tiểu uNa+-guided, hỗ trợ tuần hoàn cơ học tạm thời). Phần 4 — suy tim nặng/giai đoạn D (chương 8: tiêu chuẩn chẩn đoán, sàng lọc 'Rule of three'/'I NEED HELP', INTERMACS, LVAD BTT/BTC/BTR/liệu pháp đích, ghép tim, chăm sóc cuối đời). Phần 5 — bệnh đồng mắc tim mạch & ngoài tim mạch (chương 9–10: rung nhĩ/CHA2DS2-VA, bệnh mạch vành, bệnh van tim/TEER, tăng huyết áp, béo phì, đái tháo đường — bảng an toàn thuốc, bệnh thận mạn, thiếu sắt — định nghĩa mới TSAT<20%, rối loạn thở khi ngủ — ASV chống chỉ định ở ngưng thở trung ương, trầm cảm, suy yếu). Mỗi phần có sơ đồ SVG tự vẽ minh họa và bảng bẫy thi MCQ riêng.",
      updated: "2026-09-28", url: "docs/esc-2026-suy-tim-index.html" },

    { id: "tm-dyslipidemia-2026-p1", sp: "tm", topic: "Rối loạn lipid máu", title: "2026 ACC/AHA Guideline Quản lý Rối loạn lipid máu — Bản dịch đầy đủ",
      org: "ACC/AHA (Circulation 2026;153:e1154–e1276)", year: 2026, doi: "https://doi.org/10.1161/CIR.0000000000001423", status: 2,
      cat: "Đầy đủ · Guideline thay thế 2018",
      note: "Bản dịch đầy đủ, chia 3 phần đọc liền trong 1 trang: (1) Tóm tắt/10 thông điệp, khung COR/LOE, định nghĩa CKM/ASCVD, sàng lọc, đo TC/LDL-C/HDL-C/TG/non-HDL-C/ApoB/Lp(a), theo dõi & bảng mục tiêu lipoprotein, quản lý lối sống. (2) Điều trị dược lý (statin & không statin), PREVENT-ASCVD & khung CPR, yếu tố tăng nguy cơ/nguy cơ sinh sản/điểm đa gen, chỉ định CAC, tăng cholesterol máu nặng & FH/HoFH, đái tháo đường, phòng ngừa thứ phát, quản lý xơ vữa dưới lâm sàng, trẻ em/người trẻ/người cao tuổi. (3) Thai kỳ/cho con bú, chủng tộc/sắc tộc, suy tim, bệnh viêm mạn, CKD, HIV, ung thư, tăng triglyceride máu, tiếp cận Lp(a) cao, hội chứng cơ do statin, an toàn thuốc & tương tác thuốc, khoảng trống bằng chứng. 15 sơ đồ/thuật toán gốc được nhúng dạng ảnh; các bảng số liệu dựng lại thành HTML tiếng Việt.",
      updated: "2026-09-27", url: "docs/dyslipidemia-2026-phan1.html" },

    { id: "tm-aspirin-lam-sang-hien-dai", sp: "tm", topic: "Kháng kết tập tiểu cầu", title: "Vị thế của Aspirin trong dòng chảy Tim mạch hiện đại — Tổng hợp lâm sàng",
      org: "Bài giảng BS. Trần Tuấn Anh — tổng hợp từ các RCT và khuyến cáo 2026", year: 2026, doi: "", status: 2,
      cat: "Aspirin & DAPT",
      note: "Từ vỏ liễu đến cơ chế phân tử; 3 RCT bản lề 2018 đã đổi hướng dự phòng tiên phát; so sánh Aspirin/Clopidogrel/Ticagrelor/Prasugrel, CYP2C19 và \"nghịch lý Đông Á\"; DAPT sau ACS/PCI, xu hướng rút ngắn và xuống thang; PREMIUM (bỏ Aspirin từ đầu trong STEMI cấp?), A-CLOSE (duy trì Aspirin hay Clopidogrel sau 12 tháng); thuật toán quyết định kháng kết tập tiểu cầu theo mốc thời gian sau PCI.",
      updated: "2026-09-27", url: "https://huuhuynh2k2-droid.github.io/aspirin-trong-lam-sang-hien-dai/" },

    { id: "hour1-sepsis-bundle", sp: "hscc", topic: "Sepsis và sốc nhiễm khuẩn", title: "Hour-1 Sepsis Bundle: cập nhật bằng chứng (Gói can thiệp Hour-1 trong sepsis)",
      org: "J. Clin. Med. (bài tổng quan về hướng dẫn SSC 2026)", year: 2026, doi: "https://doi.org/10.3390/jcm15156049", status: 2,
      cat: "Bài tổng quan",
      note: "Điểm lại 5 thành phần của Hour-1 Bundle theo hướng dẫn SSC 2026: đo lactate, cấy máu trước kháng sinh, kháng sinh phổ rộng, dịch tinh thể (30 mL/kg chỉ là điểm khởi đầu), thuốc vận mạch (norepinephrine sớm, MAP khoảng 65 mmHg).",
      updated: "2026-09-27", url: "docs/hour1-sepsis-bundle.html" },

    { id: "ada-2026-muc-tieu-duong-huyet", sp: "nt", topic: "Đái tháo đường", title: "Mục tiêu đường huyết, hạ đường huyết và cơn tăng đường huyết cấp",
      org: "ADA Standards of Care — Chương 6", year: 2026, doi: "https://doi.org/10.2337/dc26-S006", status: 2,
      cat: "",
      note: "Mục tiêu A1C/TIR cá thể hóa, đánh giá và phòng ngừa hạ đường huyết, xử trí DKA/HHS.",
      updated: "2026-09-16", url: "https://huuhuynh2k2-droid.github.io/muc-tieu-duong-huyet/" },

    { id: "ada-2026-quan-ly-dh-noi-vien", sp: "nt", topic: "Đái tháo đường", title: "Quản lý đường huyết nội viện",
      org: "ADA Standards of Care — Chương 16", year: 2026, doi: "", status: 2,
      cat: "Nội viện",
      note: "Mục tiêu đường huyết ICU/ngoài ICU, phác đồ insulin theo bối cảnh (hồi sức, nuôi ăn qua sonde, dùng corticoid), xử trí quanh phẫu thuật.",
      updated: "", url: "https://huuhuynh2k2-droid.github.io/ki-m-so-t-ng-huy-t/" },

    { id: "cls-lo-trinh-t10-2026", sp: "cls", topic: "Lộ trình", title: "Lộ trình Cận lâm sàng tháng 10/2026 — lịch học và mục lục 58 bài",
      org: "Kế hoạch học tập cá nhân", year: 2026, status: 2,
      cat: "Kế hoạch · 4 tuần · 41 bài đợt 1 + 17 bài đợt 2 · có ô đánh dấu đã học",
      note: "Sơ đồ lộ trình 4 tuần, lịch theo từng ngày 07–31/10, mục lục chi tiết các mục của từng bài theo 13 nhóm: nền tảng diễn giải, gan–mật–tụy, CĐHA bụng, huyết học–đông máu, nhiễm khuẩn–vi sinh, thận–nước tiểu, điện giải–toan kiềm, tim mạch, nội tiết, hô hấp, thần kinh, miễn dịch, độc chất.",
      updated: "2026-10-06", url: "docs/lo-trinh-can-lam-sang-thang-10.html" },
    { id: "cls-0-1", sp: "cls", topic: "0 · Nền tảng diễn giải xét nghiệm", title: "0.1 · Nguyên lý đọc xét nghiệm: độ nhạy, độ đặc hiệu, tỷ số khả dĩ và sai số tiền phân tích",
      org: "Chuyên đề tổng hợp: BMJ Statistics Notes (Altman & Bland 1994; Deeks & Altman 2004) · Ozarda, Biochem Med 2016 · Badrick, Pract Lab Med 2021 · Tóth, eJIFCC 2020 · Lima-Oliveira, Biochem Med 2014", year: 2026,
      doi: "https://doi.org/10.1136/bmj.329.7458.168", status: 2,
      cat: "Chuyên đề cận lâm sàng · Tổng hợp 8 nguồn · 3 sơ đồ tự vẽ + 1 hình gốc · 16 bẫy MCQ",
      note: "Bảng 2×2 và Se/Sp (xạ hình gan 231/32/27/54: Se 0,90, Sp 0,63); PPV/NPV phụ thuộc tỷ lệ hiện mắc (0,88/0,59 khi P 0,75 so với 0,45/0,95 khi P 0,25; Se=Sp=95%, P 1% → PPV 16%); LR+ = Se/(1−Sp), LR > 10 / < 0,1, LR nhiều mức (hút thuốc gói-năm), odds hậu nghiệm = odds tiền nghiệm × LR (10% → 69%), toán đồ Fagan, ngưỡng loại trừ–ngưỡng điều trị; khoảng tham chiếu bách phân vị 2,5–97,5, ≥ 120 người, 5% người khỏe ngoài khoảng, 1 − 0,95ⁿ, khoảng tham chiếu vs ngưỡng quyết định, chỉ số cá thể (creatinin); RCV = z√2√(CVa²+CVi²), ALT ~57%, AST ~39%; tán huyết (4% mẫu, < 2% thật, 0,5 g/L, LDH/K/AST), nhiễm EDTA (5% → K +15%, Ca −12%, Mg −23%), thứ tự lấy ống; sơ đồ xử trí kết quả bất thường không khớp lâm sàng.",
      updated: "2026-10-06", url: "docs/cls-0-1-nguyen-ly-doc-xet-nghiem.html" },
    { id: "cls-a1", sp: "cls", topic: "A · Gan – Mật – Tụy", title: "A1 · Bộ xét nghiệm gan: AST, ALT, ALP, GGT và tỷ số R",
      org: "Chuyên đề tổng hợp: BSG 2018 (Newsome, Gut) · ACG 2017 (Kwo, Am J Gastroenterol) · AFP 2017 (Oh) · Botros & Sikaris 2013 · Waseem & Chen 2016", year: 2026,
      doi: "https://doi.org/10.1136/gutjnl-2017-314924", status: 2,
      cat: "Chuyên đề cận lâm sàng · Tổng hợp 5 nguồn · 2 sơ đồ tự vẽ + hình gốc BSG · 18 bẫy MCQ",
      note: "Men gan là chỉ dấu tổn thương, không phải chức năng; sinh hóa AST (bào tương + ty thể 80%) vs ALT (bào tương), gan AST/ALT 2,5, tim/cơ 17, t½ AST 18 giờ / ALT 36 giờ, vitamin B6; ALT bình thường thật nam 29–33, nữ 19–25 U/L (ACG); phân độ < 2×, 2–5×, 5–15×, > 15×, > 10.000; tỷ số R (> 5 / < 2 / 2–5); bảng nguyên nhân AST>ALT, ALT>AST, ngoài gan; viêm gan thiếu oxy (đỉnh 24 giờ, giảm ½ sau 24–72 giờ, LDH, tử vong 56–59%); tỷ số De Ritis theo bệnh cảnh; AST tăng đơn độc; ALP gan hay xương, GGT (ACG vs BSG); sơ đồ BSG xử trí xét nghiệm gan bất thường, bộ tìm nguyên nhân chuẩn/mở rộng, 84% còn bất thường sau 1 tháng, ACG theo mức tăng, FIB-4/NFS; statin, thai, sắt, Wilson, tự miễn.",
      updated: "2026-10-06", url: "docs/cls-a1-men-gan-ty-so-r.html" },
    { id: "cls-a2", sp: "cls", topic: "A · Gan – Mật – Tụy", title: "A2 · Bilirubin và tiếp cận vàng da",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 5 08/10/2026",
      note: "Mục dự kiến: Chuyển hóa bilirubin: gián tiếp – trực tiếp – urobilinogen; Tăng bilirubin gián tiếp: tan máu, Gilbert, thuốc; Tăng bilirubin trực tiếp: tại gan và sau gan (tắc mật); Bilirubin niệu, urobilinogen niệu, màu phân; Delta-bilirubin: vì sao vàng da giảm chậm sau giải phóng tắc mật; Sơ đồ tiếp cận vàng da: xét nghiệm → siêu âm → MRCP/ERCP/EUS; Gắn với luân khoa Ngoại tiêu hóa: tắc mật, u đầu tụy, sỏi ống mật chủ.",
      updated: "2026-10-06" },
    { id: "cls-a3", sp: "cls", topic: "A · Gan – Mật – Tụy", title: "A3 · Chức năng tổng hợp gan và đánh giá xơ hóa: albumin, INR, Child-Pugh, MELD, FIB-4, FibroScan",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 5 08/10/2026",
      note: "Mục dự kiến: Albumin (t½ ~20 ngày) và INR (yếu tố VII, t½ ~6 giờ): đo gì, nhiễu gì; INR trong xơ gan không phản ánh nguy cơ chảy máu (cân bằng đông máu mới); Child-Pugh, MELD, MELD-Na, MELD 3.0: thành phần và ứng dụng; Chấm điểm xơ hóa không xâm lấn: FIB-4, APRI, ELF; Đo độ đàn hồi gan (FibroScan, ngưỡng kPa), CAP đánh giá nhiễm mỡ; Amoniac máu: khi nào có ích, khi nào không.",
      updated: "2026-10-06" },
    { id: "cls-a4", sp: "cls", topic: "A · Gan – Mật – Tụy", title: "A4 · Marker viêm gan virus: HBV, HCV, HAV, HEV",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 6 09/10/2026",
      note: "Mục dự kiến: HBV: HBsAg, anti-HBs, anti-HBc IgM/IgG, HBeAg/anti-HBe, HBV DNA, qHBsAg; Bảng diễn giải các kiểu huyết thanh HBV (cấp, mạn, đã khỏi, đã tiêm vắc-xin, anti-HBc đơn độc); Giai đoạn HBV mạn và chỉ định điều trị theo HBV DNA/ALT; Sàng lọc trước hóa trị/ức chế miễn dịch: nguy cơ tái hoạt; HCV: anti-HCV, HCV RNA, kiểu gen; anti-HCV dương nhưng RNA âm; HAV IgM, HEV IgM; viêm gan tự miễn (ANA, ASMA, IgG).",
      updated: "2026-10-06" },
    { id: "cls-a5", sp: "cls", topic: "A · Gan – Mật – Tụy", title: "A5 · Amylase, lipase và viêm tụy cấp",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 6 09/10/2026",
      note: "Mục dự kiến: Nguồn gốc, động học amylase và lipase; ngưỡng >3 lần giới hạn trên; Tiêu chuẩn Atlanta sửa đổi; khi nào cần CT (không phải thường quy lúc đầu); Tăng amylase/lipase không do tụy: suy thận, thủng tạng, tắc ruột, macroamylase, DKA; Xét nghiệm tìm nguyên nhân: triglycerid, canxi, men gan (ALT >150 gợi ý sỏi mật); Phân tầng nặng: BISAP, CRP 48 giờ, hematocrit, BUN; Không theo dõi lipase hằng ngày.",
      updated: "2026-10-06" },
    { id: "cls-a7", sp: "cls", topic: "A · Gan – Mật – Tụy", title: "A7 · Marker ung thư: AFP, CEA, CA 19-9, CA-125, PSA – dùng đúng và dùng sai",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 7 10/10/2026",
      note: "Mục dự kiến: Marker ung thư dùng để theo dõi, không để sàng lọc (trừ một số ngoại lệ); AFP và ung thư biểu mô tế bào gan: giám sát kèm siêu âm mỗi 6 tháng; CEA (đại trực tràng), CA 19-9 (tụy – mật, tăng giả khi tắc mật, âm tính ở người Lewis âm); CA-125 (buồng trứng; tăng do báng bụng, suy tim, viêm thanh mạc); PSA: tăng do viêm, sinh thiết, cưỡi xe đạp; vai trò sàng lọc có chọn lọc; Bẫy: “tầm soát ung thư bằng gói marker” ở người không triệu chứng.",
      updated: "2026-10-06" },
    { id: "cls-b2", sp: "cls", topic: "B · Chẩn đoán hình ảnh bụng & Nội soi", title: "B2 · Siêu âm bụng cho bác sĩ nội khoa",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 2 12/10/2026",
      note: "Mục dự kiến: Nguyên lý cơ bản, cửa sổ và giới hạn (hơi, béo phì); Gan: gan nhiễm mỡ, xơ gan, khối u, giãn đường mật trong gan; Túi mật và ống mật chủ: sỏi, viêm túi mật (Murphy siêu âm), đường kính OMC; Thận: ứ nước, sỏi, kích thước, phân biệt cấp và mạn; Dịch ổ bụng, dịch màng phổi, hướng dẫn chọc dò; POCUS tại giường: FAST, tĩnh mạch chủ dưới.",
      updated: "2026-10-06" },
    { id: "cls-b3", sp: "cls", topic: "B · Chẩn đoán hình ảnh bụng & Nội soi", title: "B3 · X-quang bụng và CT bụng: chỉ định, đọc cơ bản, thuốc cản quang",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 2 12/10/2026",
      note: "Mục dự kiến: X-quang bụng không chuẩn bị: liềm hơi dưới hoành, mức nước – hơi, quai ruột giãn; CT có/không cản quang, thì động mạch – tĩnh mạch cửa; CT mạch máu mạc treo; Đọc cơ bản: tắc ruột, viêm ruột thừa, viêm túi thừa, thiếu máu mạc treo, thủng tạng, sỏi niệu; Thuốc cản quang i-ốt và thận (CA-AKI): ngưỡng eGFR, dự phòng bằng dịch; Metformin và thuốc cản quang; dị ứng thuốc cản quang và tiền mê; Liều bức xạ và chọn MRI/siêu âm khi nào.",
      updated: "2026-10-06" },
    { id: "cls-c1", sp: "cls", topic: "C · Huyết học – Đông máu", title: "C1 · Công thức máu dòng hồng cầu và tiếp cận thiếu máu (MCV, RDW, hồng cầu lưới)",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 3 13/10/2026",
      note: "Mục dự kiến: Hb, Hct, MCV, MCH, MCHC, RDW: ý nghĩa và cách máy đo; Thiếu máu hồng cầu nhỏ: thiếu sắt, thalassemia (chỉ số Mentzer), bệnh mạn tính, nguyên bào sắt; Thiếu máu hồng cầu to: B12/folate, rượu, bệnh gan, suy giáp, thuốc, loạn sinh tủy; Thiếu máu hồng cầu bình thường: hồng cầu lưới tăng (mất máu, tan máu) hay giảm (suy tủy, thận); Chỉ số hồng cầu lưới hiệu chỉnh; Đa hồng cầu: nguyên phát (JAK2) và thứ phát (EPO).",
      updated: "2026-10-06" },
    { id: "cls-c4", sp: "cls", topic: "C · Huyết học – Đông máu", title: "C4 · Sắt, ferritin, độ bão hòa transferrin, vitamin B12, folate",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 3 13/10/2026",
      note: "Mục dự kiến: Chu trình sắt và hepcidin; Ferritin: marker dự trữ nhưng cũng là chất phản ứng pha cấp; Ngưỡng thiếu sắt: ferritin <30; trong viêm/suy tim/CKD: ferritin <100 hoặc 100–300 kèm TSAT <20%; Thiếu sắt kèm thiếu máu bệnh mạn tính; B12: ngưỡng xám, methylmalonic acid, homocystein; folate; Quá tải sắt: TSAT >45%, ferritin cao, gen HFE.",
      updated: "2026-10-06" },
    { id: "cls-c2", sp: "cls", topic: "C · Huyết học – Đông máu", title: "C2 · Bạch cầu và phết máu ngoại vi: giảm bạch cầu, tăng ái toan, tế bào bất thường",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 4 14/10/2026",
      note: "Mục dự kiến: Ôn nhanh từ chuyên đề marker viêm: công thức bạch cầu, chuyển trái; Giảm BCTT: phân độ, nguyên nhân thuốc (methimazole, clozapine, cotrimoxazol), sắc tộc; Giảm lympho, tăng ái toan (>1,5 G/L), tăng mono; Đọc phết máu: blast, mảnh vỡ hồng cầu, hồng cầu hình cầu, thể Howell-Jolly, giọt nước; Giảm ba dòng: tiếp cận và khi nào làm tủy đồ.",
      updated: "2026-10-06" },
    { id: "cls-c3", sp: "cls", topic: "C · Huyết học – Đông máu", title: "C3 · Tiểu cầu: giảm tiểu cầu, tăng tiểu cầu, HIT và bệnh vi mạch huyết khối",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 4 14/10/2026",
      note: "Mục dự kiến: Giả giảm tiểu cầu do EDTA (ống citrate); Giảm tiểu cầu: giảm sản xuất, tăng phá hủy, ứ ở lách, pha loãng; Ngưỡng an toàn cho thủ thuật và truyền tiểu cầu; HIT: thang 4T, kháng thể anti-PF4, xử trí; TTP/HUS: mảnh vỡ hồng cầu, LDH, PLASMIC score, ADAMTS13; Tăng tiểu cầu phản ứng hay nguyên phát (JAK2, CALR, MPL).",
      updated: "2026-10-06" },
    { id: "cls-c5", sp: "cls", topic: "C · Huyết học – Đông máu", title: "C5 · Xét nghiệm tan máu: LDH, haptoglobin, bilirubin gián tiếp, Coombs",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 5 15/10/2026",
      note: "Mục dự kiến: Tan máu trong lòng mạch và ngoài lòng mạch; Bộ ba: LDH ↑, haptoglobin ↓, bilirubin gián tiếp ↑; hồng cầu lưới ↑; Nghiệm pháp Coombs trực tiếp: tan máu tự miễn ấm/lạnh, do thuốc; Tan máu Coombs âm: G6PD (rất quan trọng ở Việt Nam), hồng cầu hình cầu, mảnh vỡ hồng cầu; Hemoglobin niệu, hemosiderin niệu.",
      updated: "2026-10-06" },
    { id: "cls-c6", sp: "cls", topic: "C · Huyết học – Đông máu", title: "C6 · Đông máu: PT/INR, aPTT, fibrinogen, D-dimer, DIC và theo dõi thuốc chống đông",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 5 15/10/2026",
      note: "Mục dự kiến: Mô hình đông máu dựa trên tế bào và vì sao PT/aPTT là xét nghiệm trong ống nghiệm; PT kéo dài đơn độc, aPTT kéo dài đơn độc, cả hai kéo dài: tiếp cận; Nghiệm pháp trộn (mixing test), kháng đông lupus; D-dimer: độ nhạy cao, ngưỡng theo tuổi, YEARS, không dùng khi xác suất cao; DIC: thang điểm ISTH; Theo dõi heparin (aPTT, anti-Xa), warfarin (INR), DOAC (khi nào cần đo); Đông máu toàn phần (TEG/ROTEM) – khái niệm.",
      updated: "2026-10-06" },
    { id: "cls-marker-viem-bc-crp-pct", sp: "cls", topic: "D · Nhiễm khuẩn – Vi sinh", title: "D1 · Vai trò các marker phản ứng viêm trong bệnh nội khoa: Bạch cầu, CRP, Procalcitonin",
      org: "Chuyên đề tổng hợp: ADLM/AACC PCT guidance · SSC 2021 · IDSA/ATS 2019 · NICE · Sager BMC Med 2017 · AFP 2015 · CCJM 2019 · ProHOSP, PRORATA, SAPS, ProACT, ADAPT-Sepsis 2025", year: 2026,
      doi: "https://doi.org/10.1186/s12916-017-0795-7", status: 2,
      cat: "Chuyên đề cận lâm sàng · Tổng hợp nhiều nguồn · 4 sơ đồ tự vẽ · 18 bẫy MCQ",
      note: "Bản chất từng marker (BC: phân bố lại/demargination; CRP: gan–IL-6, gấp đôi mỗi 8 giờ, đỉnh 36–50 giờ, t½ 19 giờ; PCT: CALC-1 ngoài tuyến giáp, IFN-γ ức chế, t½ ~24 giờ), sơ đồ động học theo giờ; ngưỡng (hs-CRP, NICE CRP tại chỗ <20/20–100/>100; PCT <0,1/0,25/0,5), hiệu chỉnh suy thận; bảng nhạy/đặc hiệu theo bệnh cảnh; dương tính/âm tính giả; đọc phối hợp CRP–PCT; thuật toán PCT ngừng kháng sinh; ADAPT-Sepsis; kế hoạch theo dõi theo 11 bệnh cảnh; tiếp cận tăng bạch cầu.",
      updated: "2026-10-06", url: "docs/marker-viem-bach-cau-crp-procalcitonin.html" },
    { id: "cls-d3", sp: "cls", topic: "D · Nhiễm khuẩn – Vi sinh", title: "D3 · Cấy máu: chỉ định, kỹ thuật lấy mẫu, nhiễm bẩn và diễn giải",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 6 16/10/2026",
      note: "Mục dự kiến: Khi nào cấy máu (và khi nào không: sốt đơn độc sau mổ, viêm mô tế bào nhẹ); 2 bộ × 2 chai, 20 mL mỗi bộ, hai vị trí; lấy trước kháng sinh; Thời gian mọc và ý nghĩa; cấy máu qua catheter (chênh thời gian mọc ≥2 giờ); Vi khuẩn nhiễm bẩn hay thật: tụ cầu coagulase âm, Corynebacterium, Bacillus; Vi khuẩn luôn coi là thật: S. aureus, Candida, S. pneumoniae, Gram âm; S. aureus máu: cấy lại, siêu âm tim; cấy máu theo dõi khi nào cần.",
      updated: "2026-10-06" },
    { id: "cls-d4", sp: "cls", topic: "D · Nhiễm khuẩn – Vi sinh", title: "D4 · Nhuộm Gram, kháng sinh đồ, MIC và cách đọc phiếu vi sinh",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 6 16/10/2026",
      note: "Mục dự kiến: Nhuộm Gram: đọc nhanh định hướng kháng sinh; Kháng sinh đồ: S – I (tăng liều) – R theo EUCAST/CLSI; MIC và điểm gãy; không so MIC giữa các kháng sinh khác nhau; Các kiểu kháng thuốc: MRSA, ESBL, AmpC, CRE (KPC, NDM, OXA-48), VRE; Xét nghiệm nhanh định danh và gen kháng thuốc (PCR multiplex, MALDI-TOF); Mẫu đờm đạt chuẩn (Bartlett), mẫu nước tiểu, mẫu mủ.",
      updated: "2026-10-06" },
    { id: "cls-d5", sp: "cls", topic: "D · Nhiễm khuẩn – Vi sinh", title: "D5 · Xét nghiệm lao: AFB, Xpert MTB/RIF, cấy, IGRA/TST, ADA dịch",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 7 17/10/2026",
      note: "Mục dự kiến: Soi AFB đờm: độ nhạy, số mẫu; Xpert MTB/RIF Ultra: phát hiện và kháng rifampicin; trace call; Cấy MGIT, kháng sinh đồ lao, LPA; Lao ngoài phổi: ADA dịch màng phổi/màng bụng, dịch não tủy, giải phẫu bệnh; Lao tiềm ẩn: IGRA và TST; trước sinh học/ức chế miễn dịch; LAM nước tiểu ở người HIV.",
      updated: "2026-10-06" },
    { id: "cls-d6", sp: "cls", topic: "D · Nhiễm khuẩn – Vi sinh", title: "D6 · Huyết thanh học và PCR: HIV, Dengue, sốt mò, leptospira, giang mai",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 2 19/10/2026",
      note: "Mục dự kiến: Kháng nguyên – kháng thể – PCR: chọn theo ngày bệnh; HIV: test kết hợp kháng nguyên/kháng thể, giai đoạn cửa sổ, tải lượng, CD4; Dengue: NS1 (ngày 1–5), IgM/IgG; dấu hiệu cận lâm sàng cảnh báo (Hct tăng, tiểu cầu giảm); Sốt mò (IgM, PCR), leptospira (MAT, IgM), thương hàn (cấy máu > Widal); Giang mai: test không đặc hiệu (RPR) và đặc hiệu (TPHA), thuật toán ngược; PCR đa mầm bệnh hô hấp/tiêu hóa/màng não: khi nào đáng làm.",
      updated: "2026-10-06" },
    { id: "cls-e1", sp: "cls", topic: "E · Thận – Nước tiểu", title: "E1 · Creatinin, eGFR, cystatin C, ure và tỷ BUN/creatinin",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 2 19/10/2026",
      note: "Mục dự kiến: Creatinin: nguồn gốc, vì sao trễ trong AKI, ảnh hưởng của cơ, thuốc (trimethoprim, cimetidine); eGFR CKD-EPI 2021 (không dùng hệ số chủng tộc), Cockcroft-Gault để chỉnh liều thuốc; Cystatin C và eGFR kết hợp: khi nào dùng; Ure/BUN: xuất huyết tiêu hóa, corticoid, dị hóa; tỷ BUN/creatinin >20; Tiêu chuẩn KDIGO AKI (liên kết bài KDIGO 2026); eGFR không dùng được khi creatinin chưa ổn định.",
      updated: "2026-10-06" },
    { id: "cls-e2", sp: "cls", topic: "E · Thận – Nước tiểu", title: "E2 · Tổng phân tích nước tiểu và cặn lắng",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 3 20/10/2026",
      note: "Mục dự kiến: Tỷ trọng, pH, glucose, ceton, bilirubin, urobilinogen; Bạch cầu esterase, nitrit: giá trị và giới hạn; Máu niệu que dương nhưng không hồng cầu: myoglobin, hemoglobin; Cặn lắng: trụ hồng cầu (viêm cầu thận), trụ hạt nâu bùn (hoại tử ống thận), trụ bạch cầu, tinh thể; Hồng cầu biến dạng: nguồn cầu thận; Nhiễm khuẩn niệu không triệu chứng: không cấy, không điều trị (trừ thai, trước thủ thuật niệu).",
      updated: "2026-10-06" },
    { id: "cls-e3", sp: "cls", topic: "E · Thận – Nước tiểu", title: "E3 · Protein niệu: que thử, ACR, PCR và protein niệu 24 giờ",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 3 20/10/2026",
      note: "Mục dự kiến: Albumin niệu và protein niệu: que thử chỉ phát hiện albumin; ACR (mg/g, mg/mmol): A1–A3 theo KDIGO; PCR mẫu ngẫu nhiên thay cho nước tiểu 24 giờ; Protein niệu ngưỡng thận hư (>3,5 g/ngày), protein Bence Jones; Protein niệu thoáng qua, tư thế, sốt, gắng sức; Khi nào sinh thiết thận.",
      updated: "2026-10-06" },
    { id: "cls-e4", sp: "cls", topic: "E · Thận – Nước tiểu", title: "E4 · Điện giải niệu: FENa, FEUrea, Na niệu, áp lực thẩm thấu niệu",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 4 21/10/2026",
      note: "Mục dự kiến: FENa <1%: trước thận; giới hạn khi dùng lợi tiểu; FEUrea <35% khi đã dùng lợi tiểu; Na niệu trong hạ natri máu (SIADH vs giảm thể tích); Áp lực thẩm thấu niệu, khoảng trống thẩm thấu niệu, khoảng trống anion niệu (toan ống thận); Kali niệu, TTKG: tiếp cận hạ kali.",
      updated: "2026-10-06" },
    { id: "cls-f1", sp: "cls", topic: "F · Điện giải – Toan kiềm", title: "F1 · Natri máu và áp lực thẩm thấu",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 4 21/10/2026",
      note: "Mục dự kiến: Áp lực thẩm thấu huyết tương đo và tính; hạ natri giả và hạ natri ưu trương (glucose); Tiếp cận hạ natri: áp lực thẩm thấu máu → niệu → Na niệu → thể tích; SIADH: tiêu chuẩn, loại trừ suy giáp, suy thượng thận; Tăng natri máu: mất nước tự do, đái tháo nhạt; Theo dõi Na khi điều chỉnh: tốc độ an toàn.",
      updated: "2026-10-06" },
    { id: "cls-f2", sp: "cls", topic: "F · Điện giải – Toan kiềm", title: "F2 · Khí máu động mạch, anion gap, delta ratio, osmolal gap và lactate",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 5 22/10/2026",
      note: "Mục dự kiến: Đọc khí máu 6 bước; bù trừ dự kiến (công thức Winter); Anion gap và hiệu chỉnh theo albumin; Delta ratio: phát hiện rối loạn phối hợp; Osmolal gap: ngộ độc methanol, ethylene glycol; Lactate: type A/B, lactate và metformin, độ thanh thải lactate; Khí máu tĩnh mạch thay động mạch khi nào; SpO2 và cạm bẫy (CO, methemoglobin).",
      updated: "2026-10-06" },
    { id: "cls-f4", sp: "cls", topic: "F · Điện giải – Toan kiềm", title: "F4 · Canxi, phospho, magie, PTH và vitamin D",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 5 22/10/2026",
      note: "Mục dự kiến: Canxi toàn phần, canxi hiệu chỉnh và canxi ion hóa; Tăng canxi máu: PTH phụ thuộc hay không (ung thư, PTHrP, vitamin D, u hạt); Hạ canxi máu: PTH, magie, vitamin D, sau phẫu thuật tuyến giáp; Phospho: hội chứng nuôi ăn lại, ly giải u; Magie: hạ magie gây hạ kali và hạ canxi khó điều chỉnh; Rối loạn khoáng – xương trong CKD.",
      updated: "2026-10-06" },
    { id: "cls-g1", sp: "cls", topic: "G · Tim mạch", title: "G1 · Troponin độ nhạy cao: thuật toán 0/1 giờ, 0/2 giờ và tăng troponin không do nhồi máu",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 6 23/10/2026",
      note: "Mục dự kiến: Cấu trúc và động học troponin; bách phân vị 99; Thuật toán ESC 0/1 giờ, 0/2 giờ: loại trừ, quan sát, xác định; Định nghĩa toàn cầu lần 4 về nhồi máu cơ tim: type 1, type 2, tổn thương cơ tim; Tăng troponin không do mạch vành: viêm cơ tim, thuyên tắc phổi, sepsis, suy thận, rung nhĩ nhanh; Troponin trong CKD: dùng thay đổi động học; CK-MB còn vai trò gì.",
      updated: "2026-10-06" },
    { id: "cls-g2", sp: "cls", topic: "G · Tim mạch", title: "G2 · BNP và NT-proBNP",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 6 23/10/2026",
      note: "Mục dự kiến: Sinh lý: sức căng thành tim; BNP và NT-proBNP khác nhau thế nào; Ngưỡng loại trừ suy tim cấp và mạn; ngưỡng NT-proBNP theo tuổi; Tăng do suy thận, rung nhĩ, tuổi, thuyên tắc phổi, sepsis; Thấp giả ở người béo phì; BNP tăng khi dùng sacubitril/valsartan (dùng NT-proBNP); Theo dõi điều trị và tiên lượng (liên kết bài ESC 2026 suy tim).",
      updated: "2026-10-06" },
    { id: "cls-g3", sp: "cls", topic: "G · Tim mạch", title: "G3 · Điện tâm đồ hệ thống cho bác sĩ nội khoa",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 7 24/10/2026",
      note: "Mục dự kiến: Đọc 9 bước: nhịp, tần số, trục, P, PR, QRS, ST, T, QT; Thiếu máu cơ tim: STEMI và tương đương STEMI (de Winter, Wellens, Sgarbossa); Rối loạn nhịp nhanh, chậm; block nhĩ thất, block nhánh; Phì đại thất, lớn nhĩ; Rối loạn điện giải trên ECG (liên kết các bài kali), QTc và thuốc; Thuyên tắc phổi, viêm màng ngoài tim.",
      updated: "2026-10-06" },
    { id: "cls-g4", sp: "cls", topic: "G · Tim mạch", title: "G4 · Siêu âm tim cho bác sĩ nội khoa",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 2 26/10/2026",
      note: "Mục dự kiến: Các mặt cắt cơ bản; Phân suất tống máu và phân loại suy tim (HFrEF, HFmrEF, HFpEF); Rối loạn vận động vùng, bệnh van tim mức độ nặng; Tràn dịch màng ngoài tim, chèn ép tim; Chức năng thất phải, áp lực động mạch phổi, tĩnh mạch chủ dưới; Siêu âm tim qua thực quản: khi nào (viêm nội tâm mạc, huyết khối nhĩ).",
      updated: "2026-10-06" },
    { id: "cls-h1", sp: "cls", topic: "H · Nội tiết", title: "H1 · Glucose, HbA1c, OGTT, ceton, C-peptide và kháng thể đái tháo đường",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 2 26/10/2026",
      note: "Mục dự kiến: Tiêu chuẩn chẩn đoán đái tháo đường và tiền đái tháo đường; HbA1c sai lệch: thiếu máu, thalassemia, CKD, thai, truyền máu; fructosamine; Glucose mao mạch và CGM nội viện; Ceton máu (β-hydroxybutyrate) và ceton niệu; C-peptide, kháng thể GAD/IA-2: phân biệt típ 1, LADA, típ 2; Liên kết các bài ADA 2026 trong thư viện.",
      updated: "2026-10-06" },
    { id: "cls-h2", sp: "cls", topic: "H · Nội tiết", title: "H2 · Chức năng tuyến giáp: TSH, FT4, FT3, kháng thể và thyroglobulin",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 3 27/10/2026",
      note: "Mục dự kiến: Trục hạ đồi – tuyến yên – tuyến giáp; TSH là xét nghiệm đầu tay; Các kiểu kết quả: cường giáp, suy giáp, cận lâm sàng, TSH thấp kèm FT4 thấp (trung ương); Hội chứng bệnh lý không do tuyến giáp (sick euthyroid) ở bệnh nhân nặng; Nhiễu: biotin, amiodarone, corticoid, heparin, thai kỳ; TRAb, anti-TPO, thyroglobulin; xạ hình và siêu âm tuyến giáp (TI-RADS); Liên kết các bài cường giáp trong thư viện.",
      updated: "2026-10-06" },
    { id: "cls-h3", sp: "cls", topic: "H · Nội tiết", title: "H3 · Trục thượng thận: cortisol, ACTH, test Synacthen, test ức chế dexamethasone",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 3 27/10/2026",
      note: "Mục dự kiến: Nhịp ngày đêm của cortisol; cortisol buổi sáng: ngưỡng loại trừ, ngưỡng gợi ý; Suy thượng thận nguyên phát và thứ phát; ACTH; test Synacthen; Suy thượng thận do glucocorticoid (liên kết bài sẵn có); Hội chứng Cushing: dexamethasone 1 mg qua đêm, cortisol nước bọt nửa đêm, cortisol niệu 24 giờ; Thuốc tránh thai, estrogen làm tăng globulin gắn cortisol; Cortisol ở bệnh nhân ICU.",
      updated: "2026-10-06" },
    { id: "cls-i1", sp: "cls", topic: "I · Hô hấp", title: "I1 · X-quang ngực hệ thống",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 4 28/10/2026",
      note: "Mục dự kiến: Kỹ thuật phim: tư thế, xuyên thấu, hít vào, xoay; Đọc hệ thống ABCDE; Đông đặc, xẹp phổi, tràn dịch, tràn khí màng phổi; Phù phổi do tim và không do tim; Nốt và khối phổi; lao (hang, nốt vệ tinh); Vị trí ống nội khí quản, catheter tĩnh mạch trung tâm, sonde dạ dày.",
      updated: "2026-10-06" },
    { id: "cls-i3", sp: "cls", topic: "I · Hô hấp", title: "I3 · Chức năng hô hấp: hô hấp ký, test giãn phế quản, DLCO",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 4 28/10/2026",
      note: "Mục dự kiến: FEV1, FVC, FEV1/FVC; ngưỡng cố định 0,7 và giới hạn dưới bình thường; Tắc nghẽn, hạn chế, hỗn hợp; khi nào cần thể tích phổi; Test giãn phế quản: hen và COPD (GOLD, GINA); DLCO: giảm trong khí phế thũng, bệnh mô kẽ, tăng áp phổi; Lưu lượng đỉnh, FeNO, test kích thích phế quản.",
      updated: "2026-10-06" },
    { id: "cls-i4", sp: "cls", topic: "I · Hô hấp", title: "I4 · Dịch màng phổi: tiêu chuẩn Light, pH, glucose, ADA, tế bào",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 5 29/10/2026",
      note: "Mục dự kiến: Dịch thấm hay dịch tiết: tiêu chuẩn Light; chênh albumin khi đang dùng lợi tiểu; Tràn dịch cận viêm phổi biến chứng: pH <7,2, glucose <60 mg/dL, LDH cao → dẫn lưu; ADA và tế bào lympho: lao màng phổi; Tràn dịch ác tính: tế bào học, độ nhạy lần 1–2; Tràn máu màng phổi, dưỡng chấp (triglycerid >110 mg/dL); NT-proBNP dịch màng phổi trong suy tim.",
      updated: "2026-10-06" },
    { id: "cls-j1", sp: "cls", topic: "J · Thần kinh", title: "J1 · Dịch não tủy: chỉ định chọc dò, đọc kết quả và các kiểu viêm màng não",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 5 29/10/2026",
      note: "Mục dự kiến: Chỉ định, chống chỉ định; khi nào cần CT trước chọc dò; Áp lực mở, tế bào, protein, glucose, tỷ glucose DNT/máu; Kiểu vi khuẩn, virus, lao, nấm (cryptococcus, mực tàu, kháng nguyên); Chọc dò chạm mạch: hiệu chỉnh bạch cầu; Xuất huyết dưới nhện: dịch vàng (xanthochromia); PCR đa tác nhân và lactate dịch não tủy.",
      updated: "2026-10-06" },
    { id: "cls-j2", sp: "cls", topic: "J · Thần kinh", title: "J2 · CT và MRI não trong đột quỵ và cấp cứu thần kinh",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 6 30/10/2026",
      note: "Mục dự kiến: CT không cản quang: xuất huyết, dấu hiệu nhồi máu sớm, ASPECTS; CT mạch máu và CT tưới máu; cửa sổ thời gian tiêu sợi huyết và lấy huyết khối; MRI: DWI/FLAIR mismatch, khi nào chọn MRI; Xuất huyết dưới nhện, máu tụ dưới màng cứng; Bệnh não do tăng huyết áp (PRES), huyết khối tĩnh mạch não.",
      updated: "2026-10-06" },
    { id: "cls-k1", sp: "cls", topic: "K · Cơ xương khớp – Miễn dịch", title: "K1 · Kháng thể kháng nhân (ANA), anti-dsDNA, ENA và bổ thể",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 6 30/10/2026",
      note: "Mục dự kiến: ANA: hiệu giá, kiểu huỳnh quang; ANA dương ở người khỏe; Anti-dsDNA, anti-Sm (lupus); anti-Ro/La, anti-Scl-70, anti-centromere, anti-Jo-1; Bổ thể C3, C4 trong lupus và viêm cầu thận; Kháng thể kháng phospholipid (aCL, anti-β2GPI, kháng đông lupus); Khi nào KHÔNG nên làm ANA.",
      updated: "2026-10-06" },
    { id: "cls-k2", sp: "cls", topic: "K · Cơ xương khớp – Miễn dịch", title: "K2 · Yếu tố dạng thấp, anti-CCP, HLA-B27, acid uric và dịch khớp",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS tháng 10 · Lịch: Thứ 7 31/10/2026",
      note: "Mục dự kiến: RF và anti-CCP: độ nhạy, độ đặc hiệu, RF dương trong viêm gan C, nhiễm khuẩn; HLA-B27 và viêm cột sống; Acid uric: có thể bình thường trong cơn gout cấp; Dịch khớp: bạch cầu, tinh thể (urat âm tính lưỡng chiết mạnh, CPPD dương yếu), Gram, cấy; Ngưỡng bạch cầu dịch khớp gợi ý nhiễm khuẩn.",
      updated: "2026-10-06" },
    { id: "cls-a6", sp: "cls", topic: "A · Gan – Mật – Tụy", title: "A6 · Dịch màng bụng: SAAG, protein, bạch cầu đa nhân, cấy",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS · Đợt 2 (tháng 11)",
      note: "Mục dự kiến: SAAG ≥1,1 và protein dịch: phân loại nguyên nhân; Viêm phúc mạc nhiễm khuẩn tự phát (BCĐNTT ≥250/mm³) và thứ phát; Liên kết bài Báng bụng – chọc tháo dịch báng (BSG 2020).",
      updated: "2026-10-06" },
    { id: "cls-a8", sp: "cls", topic: "A · Gan – Mật – Tụy", title: "A8 · Xét nghiệm phân và Helicobacter pylori",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS · Đợt 2 (tháng 11)",
      note: "Mục dự kiến: Máu ẩn trong phân, FIT; calprotectin phân; C. difficile: thuật toán GDH/toxin/PCR; H. pylori: test hơi thở, kháng nguyên phân, CLO test; ngừng PPI trước test.",
      updated: "2026-10-06" },
    { id: "cls-b4", sp: "cls", topic: "B · Chẩn đoán hình ảnh bụng & Nội soi", title: "B4 · Nội soi tiêu hóa, ERCP, MRCP, EUS: chỉ định và chuẩn bị",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS · Đợt 2 (tháng 11)",
      note: "Mục dự kiến: Nội soi trên khẩn trong xuất huyết tiêu hóa (Glasgow-Blatchford); MRCP so với ERCP so với EUS trong bệnh lý đường mật – tụy; Chuẩn bị: thuốc chống đông, kháng kết tập tiểu cầu.",
      updated: "2026-10-06" },
    { id: "cls-c8", sp: "cls", topic: "C · Huyết học – Đông máu", title: "C8 · Điện di hemoglobin và thalassemia",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS · Đợt 2 (tháng 11)",
      note: "Mục dự kiến: HbA2, HbF, HbE; thalassemia α và β; Phân biệt với thiếu sắt; tư vấn di truyền.",
      updated: "2026-10-06" },
    { id: "cls-c9", sp: "cls", topic: "C · Huyết học – Đông máu", title: "C9 · Nhóm máu, phản ứng chéo và truyền máu",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS · Đợt 2 (tháng 11)",
      note: "Mục dự kiến: ABO, Rh, sàng lọc kháng thể; Ngưỡng truyền hồng cầu hạn chế (Hb 7 g/dL), phản ứng truyền máu.",
      updated: "2026-10-06" },
    { id: "cls-c7", sp: "cls", topic: "C · Huyết học – Đông máu", title: "C7 · Điện di protein huyết thanh, chuỗi nhẹ tự do và đa u tủy",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS · Đợt 2 (tháng 11)",
      note: "Mục dự kiến: Đỉnh M, immunofixation, tỷ κ/λ; Tiêu chuẩn CRAB/SLiM; MGUS.",
      updated: "2026-10-06" },
    { id: "cls-d8", sp: "cls", topic: "D · Nhiễm khuẩn – Vi sinh", title: "D8 · Xét nghiệm nấm: galactomannan, β-D-glucan, kháng nguyên Cryptococcus",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS · Đợt 2 (tháng 11)",
      note: "Mục dự kiến: Chỉ định trong bệnh nhân suy giảm miễn dịch; Dương tính giả và âm tính giả.",
      updated: "2026-10-06" },
    { id: "cls-e5", sp: "cls", topic: "E · Thận – Nước tiểu", title: "E5 · Cấy nước tiểu và nhiễm khuẩn niệu",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS · Đợt 2 (tháng 11)",
      note: "Mục dự kiến: Ngưỡng CFU, mẫu nước tiểu giữa dòng, ống thông; Nhiễm khuẩn niệu liên quan ống thông.",
      updated: "2026-10-06" },
    { id: "cls-f3", sp: "cls", topic: "F · Điện giải – Toan kiềm", title: "F3 · Kali máu (ôn và liên kết các bài kali sẵn có)",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS · Đợt 2 (tháng 11)",
      note: "Mục dự kiến: Tăng kali giả; tiếp cận tăng và hạ kali.",
      updated: "2026-10-06" },
    { id: "cls-g5", sp: "cls", topic: "G · Tim mạch", title: "G5 · Bộ lipid máu, LDL tính và đo trực tiếp, apoB, Lp(a)",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS · Đợt 2 (tháng 11)",
      note: "Mục dự kiến: Công thức Friedewald, Martin–Hopkins; xét nghiệm không nhịn đói; Liên kết bài ACC/AHA 2026 rối loạn lipid máu.",
      updated: "2026-10-06" },
    { id: "cls-g6", sp: "cls", topic: "G · Tim mạch", title: "G6 · Holter, nghiệm pháp gắng sức, CT mạch vành, chụp mạch vành",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS · Đợt 2 (tháng 11)",
      note: "Mục dự kiến: Chọn test chẩn đoán bệnh mạch vành mạn theo xác suất tiền nghiệm; Điểm canxi mạch vành.",
      updated: "2026-10-06" },
    { id: "cls-h4", sp: "cls", topic: "H · Nội tiết", title: "H4 · Aldosterone/renin, metanephrine: tầm soát tăng huyết áp thứ phát",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS · Đợt 2 (tháng 11)",
      note: "Mục dự kiến: Tỷ aldosterone/renin, thuốc gây nhiễu; Metanephrine huyết tương và niệu.",
      updated: "2026-10-06" },
    { id: "cls-h5", sp: "cls", topic: "H · Nội tiết", title: "H5 · Tuyến yên: prolactin, IGF-1, LH/FSH, test kích thích",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS · Đợt 2 (tháng 11)",
      note: "Mục dự kiến: Tăng prolactin: thuốc, macroprolactin, hiệu ứng hook; Suy tuyến yên.",
      updated: "2026-10-06" },
    { id: "cls-i2", sp: "cls", topic: "I · Hô hấp", title: "I2 · CT ngực, CT mạch phổi (CTPA) và CT liều thấp",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS · Đợt 2 (tháng 11)",
      note: "Mục dự kiến: CTPA: chỉ định theo Wells/YEARS; Bệnh phổi mô kẽ: HRCT; sàng lọc ung thư phổi.",
      updated: "2026-10-06" },
    { id: "cls-j3", sp: "cls", topic: "J · Thần kinh", title: "J3 · Điện não đồ, điện cơ và dẫn truyền thần kinh",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS · Đợt 2 (tháng 11)",
      note: "Mục dự kiến: EEG trong động kinh, trạng thái động kinh không co giật; EMG/NCS trong Guillain-Barré, bệnh thần kinh ngoại biên.",
      updated: "2026-10-06" },
    { id: "cls-k3", sp: "cls", topic: "K · Cơ xương khớp – Miễn dịch", title: "K3 · ANCA, anti-GBM, cryoglobulin và viêm mạch",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS · Đợt 2 (tháng 11)",
      note: "Mục dự kiến: c-ANCA/PR3, p-ANCA/MPO; Hội chứng phổi – thận.",
      updated: "2026-10-06" },
    { id: "cls-l3", sp: "cls", topic: "L · Độc chất – Nồng độ thuốc", title: "L3 · Độc chất và nồng độ thuốc: paracetamol, digoxin, vancomycin, lithium, aminoglycosid",
      org: "Chuyên đề tổng hợp (chưa soạn)", year: 2026, status: 0,
      cat: "Lộ trình CLS · Đợt 2 (tháng 11)",
      note: "Mục dự kiến: Toán đồ Rumack-Matthew; Nồng độ đáy, AUC vancomycin; nồng độ digoxin và kali.",
      updated: "2026-10-06" },

    { id: "nt-ada-easd-2026-dtd-tip2", sp: "nt", topic: "Đái tháo đường", title: "Đồng thuận ADA/EASD 2026 — Quản lý đái tháo đường típ 2 (bản dịch đầy đủ)",
      org: "ADA/EASD Consensus Report (Davies MJ, …, Buse JB). Diabetologia & Diabetes Care 2026", year: 2026,
      doi: "https://doi.org/10.1007/s00125-026-06855-7", status: 2,
      cat: "Đồng thuận mới nhất · Dịch đầy đủ từ PDF gốc (CC BY 4.0) · 6 hình gốc có giải thích · Bảng 1 dựng lại",
      note: "Dịch toàn văn kèm 6 hình gốc (Hình 1 chăm sóc tích hợp; Hình 2 mô hình ăn uống + bảng tác động; Hình 3a/3b năm chữ S và cách “kê đơn” vận động 24 giờ; Hình 4 sơ đồ chọn thuốc theo glucose/cân nặng/ASCVD/CKD/HF/MASLD; Hình 5 SGLT2i vs GLP-1 theo kiểu hình; Hình 6 hệ thống y tế học hỏi), Bảng 1 (8 nhóm thuốc × 12 thông số) dựng lại HTML, đủ 70 khuyến cáo đồng thuận. Điểm chính: SGLT2i và/hoặc liệu pháp dựa trên GLP-1 sớm có thể từ lúc chẩn đoán; phối hợp sớm khi CVD+CKD+suy tim; finerenone (eGFR >25, UACR >30 mg/g); semaglutide/tirzepatide trong HFpEF béo phì, MASH (ESSENCE, SYNERGY-NASH), OSA (SURMOUNT-OSA), PAD (STRIDE, SOUL); orforglipron, icodec, efsitora; phẫu thuật chuyển hóa BMI ≥27,5/32,5 ở người châu Á; sàng lọc tăng cortisol máu khi kháng trị; insulin nền sau GLP-1, ngừng sulfonylurea; DSMES 4 thời điểm; khoảng trống kiến thức và phụ lục bẫy MCQ.",
      updated: "2026-10-05", url: "docs/dong-thuan-ada-easd-2026-dtd-tip-2.html" },

    { id: "nt-ada2026-ch16-dh-noi-vien-dka", sp: "nt", topic: "Đái tháo đường", title: "Kiểm soát đường huyết nội viện theo ADA 2026: từ insulin nền–bữa ăn đến DKA/HHS",
      org: "ADA Standards of Care 2026 — Chương 16 (+ Chương 9) · slide BS Trần Tuấn Anh · bổ sung nghiên cứu gốc", year: 2026,
      doi: "https://doi.org/10.2337/dc26-S016", status: 2,
      cat: "Nội viện · DKA/HHS · Bản tổng hợp/biên soạn lại · 27 hình gốc + 1 sơ đồ tự vẽ",
      note: "Khung theo slide BS Trần Tuấn Anh: sinh lý và dược động học insulin (bảng Petznick), HbA1c khi nhập viện (16.1), mục tiêu ICU 140–180/ngoài ICU 100–180 (16.4–16.5) kèm NICE-SUGAR; basal-bolus vs sliding scale (16.8–16.10), tính TDD 0,3–0,6 UI/kg, chuyển TM → dưới da 60–80%, thang hiệu chỉnh và quy tắc 1800; Bellido 2015 (trộn sẵn hạ ĐH 64% vs 24%); nuôi ăn sonde/PN; hạ ĐH và sai sót liều U-500; corticoid; SGLT2i trong suy tim (16.11), DPP-4i, GLP-1RA; chu phẫu (16.15); thuốc tiêm ĐTĐ típ 2 (9.20–9.23), quá liều nền, trộn 2–3 mũi, Mixtard, Dawn/Somogyi, IDegAsp (chuyển 1:1, chỉnh liều hàng tuần), tái sử dụng kim và loạn dưỡng mỡ; DKA/HHS (16.16–16.17): tiêu chuẩn đồng thuận 2024, phân độ, ceton niệu, sơ đồ ADA 2026 Việt hóa, RL vs NaCl (Trifi 2026), insulin nền sớm (Thammakosol 2023, Lim 2022), kali, Na hiệu chỉnh 2,4; theo dõi ĐH/CGM nội viện, phác đồ ra viện theo HbA1c, bảng 25 bẫy MCQ.",
      updated: "2026-10-05", url: "docs/kiem-soat-duong-huyet-noi-vien-ada-2026.html" },

    { id: "nt-tang-duong-huyet-noi-tru", sp: "nt", topic: "Đái tháo đường", title: "Quản lý tăng đường huyết ở bệnh nhân nội trú",
      org: "Annals of Internal Medicine — In the Clinic", year: 2024, doi: "https://doi.org/10.7326/ANNALS-24-02754", status: 2,
      cat: "Nội viện",
      note: "Bài In the Clinic đầy đủ: định nghĩa và mục tiêu đường huyết nội trú, 3 bước khởi động insulin dưới da (kèm sơ đồ gốc), thang hiệu chỉnh, DPP4i/SGLT2i/GLP-1RA, xử trí hạ đường huyết, tăng đường huyết do glucocorticoid (kèm sơ đồ liều NPH), chu phẫu, nuôi ăn qua sonde/PN, CGM, bơm insulin, và danh mục xuất viện — kèm 4 ví dụ ca lâm sàng tính liều insulin.",
      updated: "2026-09-27", url: "docs/hyperglycemia-hospitalized.html" },

    { id: "nt-cuong-giap-ata", sp: "nt", topic: "Tuyến giáp", title: "Chẩn đoán và xử trí cường giáp",
      org: "ATA", year: 2016, doi: "", status: 2,
      cat: "Basedow / cường giáp",
      note: "124 khuyến cáo dựa trên bằng chứng, chia 5 phần: nền tảng chẩn đoán, điều trị Basedow (RAI/ATD/phẫu thuật), bướu giáp đa nhân độc, cường giáp trẻ em, cường giáp dưới lâm sàng và thai kỳ, bệnh mắt Basedow.",
      updated: "", url: "https://huuhuynh2k2-droid.github.io/Tuyen-giap-ATA-2026/" },

    { id: "nt-cuong-giap-2018", sp: "nt", topic: "Tuyến giáp", title: "Xử trí cường giáp Basedow",
      org: "ETA", year: 2018, doi: "", status: 2,
      cat: "Basedow / cường giáp",
      note: "Hướng dẫn của Hiệp hội Giáp châu Âu (ETA) 2018, 50 khuyến cáo theo hệ GRADE: xét nghiệm, chẩn đoán hình ảnh, kháng giáp tổng hợp, I-131, phẫu thuật, và các nhóm đặc biệt (thai kỳ, cao tuổi, trẻ em).",
      updated: "", url: "https://huuhuynh2k2-droid.github.io/C-ng-Gi-p-ATA-2018/" },

    { id: "nt-suy-thuong-than-gc", sp: "nt", topic: "Tuyến thượng thận", title: "Suy thượng thận do Glucocorticoid — Chẩn đoán và Điều trị",
      org: "ESE / Endocrine Society", year: 2024, doi: "https://doi.org/10.1210/clinem/dgae250", status: 2,
      cat: "",
      note: "Hướng dẫn phối hợp ESE/Endocrine Society 2024: tư vấn khi dùng glucocorticoid kéo dài, giảm liều và chẩn đoán suy thượng thận do GC, xử trí cơn suy thượng thận cấp.",
      updated: "", url: "https://huuhuynh2k2-droid.github.io/chot-suy/" },

    { id: "tq-tang-kali-mau-cap", sp: "tq", topic: "Rối loạn điện giải", title: "Chẩn đoán và xử trí tăng kali máu cấp",
      org: "BMJ / KDIGO / ERC", year: 2026, doi: "https://doi.org/10.1136/bmj-2026-100287", status: 2,
      cat: "Tăng kali máu · Cấp cứu",
      note: "Chiến lược 3 bước cấp cứu: ổn định màng cơ tim (Calcium IV), đưa K+ vào nội bào (Insulin+Glucose, Salbutamol), tăng thải K+ (lợi tiểu, resin, lọc máu).",
      updated: "2026-09-16", url: "https://huuhuynh2k2-droid.github.io/tangkali/" },

    { id: "tq-kali-nen-ecg", sp: "tq", topic: "Rối loạn điện giải", title: "Kali máu nền và biến đổi ECG trong tăng kali máu",
      org: "Nakayama 2025", year: 2025, doi: "https://doi.org/10.1111/nep.70100", status: 2,
      cat: "Tăng kali máu · ECG",
      note: "Bệnh nhân có kali nền thấp có nguy cơ biến đổi ECG cao hơn khi tăng kali máu; mức thay đổi kali (ΔK) dự đoán tốt hơn giá trị tuyệt đối.",
      updated: "", url: "https://huuhuynh2k2-droid.github.io/ecg-kalinen-tang-kalimau/" },

    { id: "tq-tuong-quan-kali-ecg", sp: "tq", topic: "Rối loạn điện giải", title: "ECG và tăng kali máu — Tổng hợp 34 năm nghiên cứu (1991–2025)",
      org: "", year: null, doi: "", status: 2,
      cat: "Tăng kali máu · ECG",
      note: "Dòng thời gian 11 nghiên cứu mốc, 4 giai đoạn (1991–2025) về tương quan mức tăng kali máu và biến đổi ECG. ECG có độ nhạy thấp (19–74%); QRS giãn rộng và nhịp chậm dự đoán tốt hơn sóng T nhọn kinh điển.",
      updated: "", url: "https://huuhuynh2k2-droid.github.io/ecg-tangkali-mau/" },

    { id: "tq-dieu-tri-ha-kali", sp: "tq", topic: "Rối loạn điện giải", title: "Điều trị hạ kali máu",
      org: "Oxford University Hospitals NHS", year: 2022, doi: "", status: 2,
      cat: "Hạ kali máu",
      note: "Định nghĩa, nguyên nhân, đường uống và tĩnh mạch, liều dùng và theo dõi, giới hạn an toàn khi bù kali.",
      updated: "", url: "https://huuhuynh2k2-droid.github.io/ha-kali-mau/" }
  ]
};
